name: NodeJs CI
on:
  push:
    branches:
      - master

jobs:
  cart:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installing npm dependencies
        run: npm ci
      - name: Running tests
        run: npm test
      - name: Creating npm package
        run: npm run build
